### ISSUE TITLE
echo example consumes 100% CPU

### ISSUE THREAD

**Issue by astraw** [dwrensha/gjio#2]
Hi, I was surprised that the echo example consumes 100% CPU (master branch, Mac OS X) even when nothing is connected. Is this expected?

**Comment by dwrensha** [comment]
Eek. That's a bug. I've reproduced it on my end. Investigating...

**Comment by dwrensha** [comment]
Looks like the problem is that we're calling `kevent` with a timeout of zero, when we should be calling it with `NULL`.

**Comment by dwrensha** [comment]
Thanks for the report. This should be fixed in https://github.com/dwrensha/gjio/commit/0c558d084f9bb6c0d58dd514c16f382fe3a0128a.

**Comment by dwrensha** [comment]
A similar problem existed on the Linux side. Fixed by: https://github.com/dwrensha/gjio/commit/a69d022adbe4866f928c9eb70754b5e63218ccbc.
