### ISSUE TITLE
Why is `wrap_raw_socket_descriptor` unsafe?

### ISSUE THREAD

**Issue by srijs** [dwrensha/gjio#3]
Hi!

I'm missing a bit of information on how exactly `wrap_raw_socket_descriptor` is unsafe and what needs to be taken care of to make it work.

My use-case is that I am spawning new threads per connection, and would like to run an event loop per thread/connection. In order to do so, I need to somehow produce a `SocketStream` from my `std::net::TcpStream` (which is obtained by accepting connections synchronously on the main thread).

**Comment by dwrensha** [comment]
I agree that we should add documentation for that method!

We should also probably add a method to directly convert from a `::std::net::TcpStream`.

The important thing to note is that `wrap_raw_socket_descriptor` takes ownership of the descriptor; when the resulting `SocketStream` is dropped, the descriptor is closed. You should use `into_raw_fd()` to convert from a `TcpStream`, and everything should just work.

Note that `FromRawFd::from_raw_fd()` in the standard library also marked as unsafe. The [docs](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html) provide some justification, and that justification applies to `wrap_raw_socket_descriptor` as well.
