### ISSUE TITLE
[Question] Is it possible to group async reads together so that they happen atomically?

### ISSUE THREAD

**Issue by kc1212** [dwrensha/gjio#6]
Hi, thanks for the great library. I want to know whether it is possible to group async reads together so that they happen atomically.

Suppose I'm expecting messages in the form of `length | body`. So I have a function that first reads the length `n`, and then reads the body of the message of size `n`. But I also want to have multiple promises reading on the same `StreamSocket`. This creates a problem where the first promise may read the length, and then the second promise may read the first bit of the body.

I may not have explained my problem very well but there's a contrived example. 

``` rust
extern crate gj;
extern crate gjio;

use gj::Promise;
use gjio::{AsyncRead, AsyncWrite, SocketStream};

fn read_msg(mut r: SocketStream) -> Promise<(), ::std::io::Error> {
    let mut r2 = r.clone();
    r.read(vec![0u8], 1).then(move |buf| {
        println!("read1 {:?}", buf);
        let len: usize = buf.0[0] as usize;
        r2.read(vec![0u8; len], len).map(move |buf2| {
            println!("read2 {:?}", buf2);
            Ok(())
        })
    })
}

fn write_msg(mut w: SocketStream, mut msg: Vec<u8>) -> Promise<(), ::std::io::Error> {
    let len: u8 = msg.len() as u8;
    msg.insert(0, len);
    w.write(msg).map(|_| {
        println!("wrote msg");
        Ok(())
    })
}

pub fn main() {
    ::gj::EventLoop::top_level(|wait_scope| -> Result<(), Box<::std::error::Error>> {
        let mut event_port = try!(::gjio::EventPort::new());
        let network = event_port.get_network();
        let (reader, writer) = network.new_socket_pair().unwrap();
        let reader1 = reader.clone();

        let children = vec![
            read_msg(reader),
            read_msg(reader1),
            write_msg(writer, vec![1,2,3]),
            ];
        try!(Promise::all(children.into_iter()).wait(wait_scope, &mut event_port));
        Ok(())
    }).unwrap();
}
```

I was hoping to see one of `read_msg` to read the complete message `[3,1,2,3]` where the first 3 is the length. But instead the first `read_msg` reads a 3, and then the second `read_msg` reads a 1. Neither read a complete message.

Is there a solution to this problem? Or should I think of a different way to structure my code such that the reads are chained together.

**Comment by dwrensha** [comment]
Hi!

You need to chain the reads so that they happen in sequence, like this, for example:

```
read_msg(reader).then(move|()| read_msg(reader1))
```

**Comment by kc1212** [comment]
Thanks, I thought so as well.

A problem I ran into with chaining is that I couldn't easily use `Promise::all` to get the "intermediate results" of the chain. But I took the read queue idea used in your `AsyncRead/AsyncWrite` trait where every read returns a promise of the result, but the chain is still maintained using a promise/fulfiller pair. It's working pretty well for my needs so far!
